### PR TITLE
CI/CD fixes

### PR DESCRIPTION
**Pull request by Tenavi**
Fix the CI/CD failures mentioned in [https://github.com/scipy/scipy/pull/15641#issuecomment-1489241125](https://github.com/scipy/scipy/pull/15641#issuecomment-1489241125).

- Slightly loosen the inequality KKT multiplier tolerances in `_check_kkt`. Previously required `g_eval >= -1e-14`, now require `g_eval > -1e-12`. Theoretically, if a solution satisfies the inequality constraints then they must be non-negative, but in practice sometimes they turn into small negative floats. The tests originally passed locally with the stricter tolerances, but failed on the CI/CD server side test (one multiplier was about `-2e-14`).
- Fix my formatting mistake in the `_minimize` example.

### CODE REVIEW

**Comment by Tenavi** [comment]
@mdhaber this PR addresses the CI/CD failures you found. I think the base branch needs to by updated to sync with the upstream `scipy:main`?

**Comment by andyfaff** [comment]
The best way to submit PRs in this manner, that prevents all the git mess are to:

1. `git add remote andyfaff https://github.com/andyfaff/scipy.git`
2. `git fetch andyfaff`
3. `git checkout kkt`
4. `git checkout -B mychanges`
5. <git commit>
6. `git push origin mychanges`
7. Start a PR on my fork, against my `kkt` feature branch, asking to merge in `Tenavi:mychanges`.

**Comment by Tenavi** [comment]
> The best way to submit PRs in this manner, that prevents all the git mess are to:
> 
>     1. `git add remote andyfaff https://github.com/andyfaff/scipy.git`
> 
>     2. `git fetch andyfaff`
> 
>     3. `git checkout kkt`
> 
>     4. `git checkout -B mychanges`
> 
>     5. <git commit>
> 
>     6. `git push origin mychanges`
> 
>     7. Start a PR on my fork, against my `kkt` feature branch, asking to merge in `Tenavi:mychanges`.

Ah I see thanks for those instructions. I wasn't sure how to grab changes from your fork directly. I'll close this PR and redo with the workflow you suggested.

**Comment by andyfaff** [comment]
The third step may be `git checkout andyfaff/kkt`. You can use what I wrote if you don't have a branch called kkt.

**Pull request closed without merging**
